/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 59d8caf3142296358ca762d91f608074)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		HYPERDRIVE: Hyperdrive;
		ASSETS: Fetcher;
		ADMIN_CODE: string;
		SESSION_SECRET: string;
		DATABASE_URL: string;
		DIRECT_URL: string;
		SUPABASE_URL: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
		WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_CODE" | "SESSION_SECRET" | "DATABASE_URL" | "DIRECT_URL" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
